include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    use_super_parameters: true
    prefer_relative_imports: true
    directives_ordering: true

analyzer:
  errors:
    todo: ignore
  exclude:
    - 'examples'
