name: hrk_flutter_test_batteries
version: 0.3.0

description: >-
  A library to accumulate required flutter test helper and utility codes
repository: https://github.com/hrishikesh-kadam/hrk_flutter_test_batteries
topics:
  - batteries
  - flutter-batteries
  - flutter-test-batteries

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  hrk_analysis: '>=0.1.0 <1.0.0'
  go_router: ^9.0.3

flutter:
  uses-material-design: true
