name: hrk_flutter_test_batteries
version: 0.1.0-pre.1

description: >-
  A library to accumulate required flutter test helper and utility codes
repository: https://github.com/hrishikesh-kadam/hrk_flutter_test_batteries

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
